import { StyleSheet } from 'react-native';
import { colors, typography, spacing } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.card,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xl,
    alignItems: 'center',
    marginBottom: spacing.lg,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  profileIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  profileIconText: {
    fontSize: 36,
    color: colors.card,
  },
  username: {
    fontSize: typography.title,
    fontWeight: 'bold',
    color: colors.foreground,
    marginBottom: spacing.xs,
  },
  userEmail: {
    fontSize: typography.body,
    color: colors.foreground,
    opacity: 0.7,
  },
  section: {
    backgroundColor: colors.card,
    marginHorizontal: spacing.xl,
    marginBottom: spacing.lg,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: typography.subtitle,
    fontWeight: '600',
    color: colors.foreground,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  menuIcon: {
    fontSize: 20,
    marginRight: spacing.md,
    width: 24,
    textAlign: 'center',
  },
  menuText: {
    fontSize: typography.body,
    color: colors.foreground,
    fontWeight: '500',
  },
  menuArrow: {
    fontSize: 20,
    color: colors.foreground,
    opacity: 0.5,
  },
  emergencyCard: {
    backgroundColor: colors.muted,
    marginHorizontal: spacing.xl,
    borderRadius: 16,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    borderLeftWidth: 4,
    borderLeftColor: colors.destructive,
  },
  emergencyTitle: {
    fontSize: typography.subtitle,
    fontWeight: '600',
    color: colors.foreground,
    marginBottom: spacing.sm,
  },
  emergencyText: {
    fontSize: typography.body,
    color: colors.foreground,
    opacity: 0.8,
    lineHeight: 20,
    marginBottom: spacing.md,
  },
  emergencyContact: {
    backgroundColor: colors.destructive,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  emergencyContactText: {
    fontSize: typography.body,
    color: colors.card,
    fontWeight: '600',
  },
  logoutButton: {
    backgroundColor: colors.destructive,
    marginHorizontal: spacing.xl,
    borderRadius: 16,
    padding: spacing.lg,
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  logoutText: {
    fontSize: typography.subtitle,
    color: colors.card,
    fontWeight: '600',
  },
  footer: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
    alignItems: 'center',
  },
  footerText: {
    fontSize: typography.small,
    color: colors.foreground,
    opacity: 0.6,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  footerVersion: {
    fontSize: typography.small,
    color: colors.foreground,
    opacity: 0.4,
    textAlign: 'center',
  },
});
